# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "blowfish" # UNCOMMENT THIS LINE
baseURL = "https://spidermath.github.io/"
languageCode = "en"
defaultContentLanguage = "en"

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
summaryLength = 0

buildDrafts = false
buildFuture = false

enableEmoji = true

# googleAnalytics = "G-XXXXXXXXX"

[pagination]
  pagerSize = 100

[imaging]
  anchor = 'Center'

[[cascade]]
title = 'Tags'
[cascade._target]
path = '{/blog_tags,/project_tags,/notes_tags}'

[taxonomies]
  blog_tag = "blog_tags"
  project_tag = "project_tags"
  notes_tag = "notes_tags"
  category = "categories"
  author = "authors"
  series = "series"

[permalinks.term]
  project_tags = "/projects/tags/:slug"
  blog_tags = "/blog/tags/:slug"
  notes_tags = "/notes/tags/:slug"

[permalinks.taxonomy]
  project_tags = "/projects/tags/"
  blog_tags = "/blog/tags/"
  notes_tags = "/notes/tags/"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "series"
        weight = 50

    [[related.indices]]
        name = "authors"
        weight = 20

    [[related.indices]]
        name = "date"
        weight = 10

    [[related.indices]]
      applyFilter = false
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10
